FROM mcr.microsoft.com/devcontainers/base:bullseye

RUN sudo apt update -y && sudo apt install -y build-essential curl libffi-dev libffi7 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5 pkg-config
